CodeListLibrary_project/cll/static/css/main.css

Removing additional, unnecessary .css and redirecting to standard woff2 file.

Local Font Fix update 2

---

CodeListLibrary_project/cll/test_settings.py

There is the implementation of chromedriver update. So when run tests through manage.py it estimates if new version is available. Works great on Windows. But need to test on Linux this solution because I use chromedriver --version check command

Added webdriver new version and automatic update for webdriver

---

CodeListLibrary_project/clinicalcode/db_utils.py
CodeListLibrary_project/clinicalcode/permissions.py
CodeListLibrary_project/clinicalcode/views/Phenotype.py
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/partial_history_list.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/publish.html

As discussed before this approval now fixed to approve only one phenotype and submit only one phenotype

Added update for apporval phenotype

---

CodeListLibrary_project/clinicalcode/tests/functional_tests/test_functional_other.py
CodeListLibrary_project/clinicalcode/tests/functional_tests/test_history.py
CodeListLibrary_project/clinicalcode/tests/functional_tests/test_search_filters.py

Tests fail because they did not have default collection brand tags

Added final fixes to functional tests.

---

CodeListLibrary_project/clinicalcode/views/Admin.py
CodeListLibrary_project/cll/celery.py

Adde previous data statistics functionality (collections and statistics of HDRUK site) . Data-sync will be added when it will be finished

Added celery run_statistics and collections

---

CodeListLibrary_project/cll/settings.py

amend the url / LDAP of the concept library within the gateway to enable all SerPs #602

point LDAP to all SERPs users

---

CodeListLibrary_project/clinicalcode/views/View.py
CodeListLibrary_project/cll/templates/cl-docs/contact-us.html

Two small changes:
- Fixed notifications
- Reset form on successful submit

Remove form details on submit & fix notifications

---

CodeListLibrary_project/clinicalcode/api/views/Concept.py
CodeListLibrary_project/clinicalcode/api/views/Phenotype.py
CodeListLibrary_project/cll/static/css/main.css
CodeListLibrary_project/cll/templates/clinicalcode/brand/HDRUK/about/technical-details.html
CodeListLibrary_project/cll/templates/clinicalcode/concept/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/detail_combined.html
CodeListLibrary_project/cll/templates/rest_framework/API-root-pg.html

Update API section to include R package calls, update technical details page and update pheno/concept api to include collections

Update API section in pheno/concepts page, technical details & pheno/concept API

---

CodeListLibrary_project/clinicalcode/constants.py
CodeListLibrary_project/clinicalcode/models/PhenotypeWorkingset.py
CodeListLibrary_project/clinicalcode/models/PublishedWorkingset.py
CodeListLibrary_project/clinicalcode/models/__init__.py
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/form..html

Added initial working models - PhenotypeWorkingset, PublishedWorkingset
Added Directory
Added Type constants

Workingset model and initial form/directory 

---

CodeListLibrary_project/cll/static/css/main.css
CodeListLibrary_project/cll/static/js/clinicalcode/filters/filterService.js

Small fix to styling & operators within search ranking

Fix to style & logical operator in search ranking

---

CodeListLibrary_project/clinicalcode/constants.py
CodeListLibrary_project/clinicalcode/db_utils.py
CodeListLibrary_project/cll/templates/pagination.html

Now consistent with authentication & recent changes by other commits

Changes to order filters

---

CodeListLibrary_project/clinicalcode/api/urls.py
CodeListLibrary_project/clinicalcode/api/views/PhenotypeWorkingSet.py
CodeListLibrary_project/clinicalcode/api/views/View.py
CodeListLibrary_project/clinicalcode/constants.py
CodeListLibrary_project/clinicalcode/db_utils.py
CodeListLibrary_project/clinicalcode/permissions.py
CodeListLibrary_project/clinicalcode/views/View.py
CodeListLibrary_project/cll/templates/rest_framework/API-root-pg.html

PR to resolve #831 
1. [x] Implement API for phenotype working sets
2. [x] Update API to newest standard to align with current filters & other API endpoints
3. [x] Update API documentation
4. [x] Implemented ```update``` endpoint for phenotype working sets
5. [x] Implemented ```create``` endpoint for phenotype working sets

Phenotype working set API

---

CodeListLibrary_project/clinicalcode/db_utils.py
CodeListLibrary_project/clinicalcode/urls.py
CodeListLibrary_project/clinicalcode/views/PhenotypeWorkingSet.py
CodeListLibrary_project/cll/templates/clinicalcode/concept/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/partial_history_list.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/publish.html

Merge to base of #896. PR implements task from #851 
1. [x] Implement base detail method
2. [x] Reimplement ```getHistoryPhenotypeWorkingset``` method to allow query set
3. [x] Implement ```home``` section
4. [x] Implement ```description```
5. [x] Implement ```citation requirements``` section
6. [x] Implement ```publications``` section
7. [x] Implement ```permissions``` section
9. [x] Implement ```API``` section
10. [x] Implement ```version history``` section
11. [x] Reimplement ```./phenotypeworkingset/partial_history_list.html``` 
12. [x] Implement ```attributes``` section
1. [x] Erroneous styling to tag elements in ```Concept``` and ```Phenotype``` detail page

PhenotypeWorkingSet detail

---

CodeListLibrary_project/cll/static/css/main.css
CodeListLibrary_project/cll/templates/clinicalcode/concept/concept_results.html
CodeListLibrary_project/cll/templates/clinicalcode/concept/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotype/phenotype_results.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/workingset_results.html

PhenotypeWorkingSet frontend changes

---

CodeListLibrary_project/clinicalcode/views/WorkingSetSelection.py

Working set form is broken

---

CodeListLibrary_project/clinicalcode/api/views/PhenotypeWorkingSet.py
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/detail_combined.html

Please see the following for details
- #849 
- #909

API & UI enhancements for Phenotypeworkingsets

---

CodeListLibrary_project/clinicalcode/db_utils.py
CodeListLibrary_project/clinicalcode/views/PhenotypeWorkingSet.py
CodeListLibrary_project/cll/static/css/main.css
CodeListLibrary_project/cll/static/js/clinicalcode/dataService.js
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/detail_combined.html

Concept codes in PhenotypeWorkingSet

---

CodeListLibrary_project/clinicalcode/views/PhenotypeWorkingSet.py
CodeListLibrary_project/cll/static/js/clinicalcode/workingset/selectionService.js
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/form.html

Major bugfixes 
Cleaner design 
Validation
Deletion through modal (for now)

Table improvements

---

CodeListLibrary_project/clinicalcode/urls.py
CodeListLibrary_project/clinicalcode/views/SelectPhenotype.py
CodeListLibrary_project/cll/static/js/clinicalcode/workingset/selectionService.js
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/detail_combined.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/selection_results.html

PR to resolve:
#936 
#937 
Please see issue(s) for details

Small modification to workingsets - enhancements & bug fixes

---

CodeListLibrary_project/clinicalcode/views/PhenotypeWorkingSet.py
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/form.html
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/workingset_results.html

Only deletion from row left and some enhanments

Workingset update v0.1

---

CodeListLibrary_project/clinicalcode/forms/WorkingsetForm.py
CodeListLibrary_project/clinicalcode/view_utils/workingset_db_utils.py
CodeListLibrary_project/clinicalcode/views/PhenotypeWorkingSet.py
CodeListLibrary_project/cll/templates/clinicalcode/phenotypeworkingset/form.html

Done implementation in case if table data is wrong
- Checks float number
- Cheks int number
- Repeat attributes
- If the attribute starts with the wrong number 
- If the attribute starts with special charcters

Table validation backend

---

CodeListLibrary_project/clinicalcode/views/Phenotype.py

…groups (whereas JSON export does) #983

 phenotype CSV export attributes

---

CodeListLibrary_project/cll/static/js/clinicalcode/filters/filterService.js

Small fix to filters

---

CodeListLibrary_project/clinicalcode/entity_utils/utils_ge_validator.py
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/publish.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/request_publish.html

Due to changing the way how component works in detail page. Some changes needed to show table correctly

Changed components name and showing history table 

---

CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/cll/static/scss/components/_chips.scss
CodeListLibrary_project/cll/templates/components/search/cards/clinical.html
CodeListLibrary_project/cll/templates/components/search/cards/generic.html

Post #1180 
See:
- #1184
- #1185

Grouped tasks

---

CodeListLibrary_project/clinicalcode/api/urls.py
CodeListLibrary_project/clinicalcode/urls.py
CodeListLibrary_project/clinicalcode/urls_generic_entity.py

and
make create/update urls blocked in RO mode #1167

comment old sys urls

---

CodeListLibrary_project/clinicalcode/api/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/publish_utils.py
CodeListLibrary_project/clinicalcode/permissions.py
CodeListLibrary_project/clinicalcode/templatetags/entity_publish_renderer.py
CodeListLibrary_project/clinicalcode/views/Decline.py
CodeListLibrary_project/clinicalcode/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/views/Publish.py
CodeListLibrary_project/cll/context_processors.py
CodeListLibrary_project/cll/templates/base_scss.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/create.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/detail - bootstrap.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/detail-scss.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/detail.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/detail_buttons.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/publish.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/request_publish.html
CodeListLibrary_project/cll/templates/components/details/outputs/api.html
CodeListLibrary_project/cll/templates/components/details/outputs/phenotype_clinical_code_lists.html

some changes to detail/publish 

---

CodeListLibrary_project/clinicalcode/entity_utils/constants.py
CodeListLibrary_project/dynamic_templates/clinical_coded_phenotype.json
CodeListLibrary_project/dynamic_templates/structured_data_algorithm_phenotype.json

Modified descriptions and added a new template type.

Update phenotype templates

---

CodeListLibrary_project/clinicalcode/entity_utils/concept_utils.py
CodeListLibrary_project/cll/static/js/clinicalcode/redesign/forms/clinical/conceptCreator.js
CodeListLibrary_project/cll/templates/components/create/inputs/clinical/concept.html

Allow nullable rules/components/codelists in Concept

---

CodeListLibrary_project/clinicalcode/entity_utils/concept_utils.py

Hotfix codelist implementation

---

CodeListLibrary_project/clinicalcode/entity_utils/create_utils.py
CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py
CodeListLibrary_project/dynamic_templates/clinical_coded_phenotype.json

Null values are allocated keys

---

CodeListLibrary_project/clinicalcode/admin.py
CodeListLibrary_project/clinicalcode/api/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/api/views/Template.py
CodeListLibrary_project/clinicalcode/entity_utils/api_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/constants.py
CodeListLibrary_project/clinicalcode/entity_utils/create_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/stats_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/template_utils.py
CodeListLibrary_project/clinicalcode/forms/TemplateForm.py
CodeListLibrary_project/clinicalcode/templatetags/detail_pg_renderer.py
CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py
CodeListLibrary_project/clinicalcode/views/GenericEntity.py
CodeListLibrary_project/cll/static/js/clinicalcode/redesign/forms/clinical/conceptCreator.js
CodeListLibrary_project/cll/static/js/clinicalcode/redesign/forms/clinical/publicationCreator.js
CodeListLibrary_project/cll/static/js/clinicalcode/redesign/forms/entityCreator.js
CodeListLibrary_project/cll/templates/components/create/inputs/inputbox.html
CodeListLibrary_project/cll/templates/components/create/inputs/markdown.html
CodeListLibrary_project/cll/templates/components/create/inputs/textarea.html
CodeListLibrary_project/dynamic_templates/clinical_coded_phenotype.json
CodeListLibrary_project/dynamic_templates/structured_data_algorithm_phenotype.json
CodeListLibrary_project/dynamic_templates/working_set.json

See:
- #1248
- #1249
See:
- #1250
- #1252
- #1253
- #1254

Change in requirements

---

CodeListLibrary_project/cll/static/js/clinicalcode/redesign/data/conceptUtils.js
CodeListLibrary_project/cll/static/scss/components/_accordians.scss
CodeListLibrary_project/cll/static/scss/components/_inputs.scss
CodeListLibrary_project/cll/static/scss/pages/detail.scss
CodeListLibrary_project/cll/templates/components/details/outputs/phenotype_clinical_code_lists.html

Small detail change

---

CodeListLibrary_project/cll/static/js/clinicalcode/redesign/forms/entityCreator.js

Legacy data issue

---

docker/production/os.Dockerfile

Requires testing on demo first
See: #1270

Update to python3.9-dev

---

CodeListLibrary_project/clinicalcode/entity_utils/constants.py
CodeListLibrary_project/clinicalcode/entity_utils/filter_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/stats_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/template_utils.py

Improve stats

---

CodeListLibrary_project/clinicalcode/forms/ContactUsForm.py
CodeListLibrary_project/clinicalcode/views/View.py
CodeListLibrary_project/cll/static/scss/_media.scss
CodeListLibrary_project/cll/static/scss/components/_banner.scss
CodeListLibrary_project/cll/static/scss/components/_inputs.scss
CodeListLibrary_project/cll/static/scss/pages/about.scss
CodeListLibrary_project/cll/templates/cl-docs/contact-us.html
CodeListLibrary_project/cll/templates/clinicalcode/moderation/index.html

Requires pages to be linked after about us pages are complete

Update contact-us page

---

CodeListLibrary_project/clinicalcode/api/urls.py
CodeListLibrary_project/clinicalcode/api/views/Concept.py
CodeListLibrary_project/clinicalcode/api/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/entity_utils/api_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/concept_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/gen_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/model_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/clinicalcode/views/Admin.py

* Update contact-us page
* Add spacing on banner
* Remove extra spacing
* Updated concept API to be inline with new development
* Remove legacy code
* Remove more legacy code

Update concept api (#1283)

---

CodeListLibrary_project/clinicalcode/api/urls.py
CodeListLibrary_project/clinicalcode/api/views/Concept.py
CodeListLibrary_project/clinicalcode/api/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/entity_utils/api_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/concept_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/gen_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/model_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/clinicalcode/views/Admin.py

Reverts SwanseaUniversityMedical/concept-library#1283
Merge issues from #1283 and #1288

Revert "Update concept api"

---

.gitignore
CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/clinicalcode/management/commands/clear_sessions.py
CodeListLibrary_project/clinicalcode/management/commands/dftm_migrate.py
CodeListLibrary_project/clinicalcode/tasks.py
CodeListLibrary_project/clinicalcode/urls_generic_entity.py
CodeListLibrary_project/clinicalcode/views/Admin.py
CodeListLibrary_project/clinicalcode/views/adminTemp.py
CodeListLibrary_project/cll/celery.py
CodeListLibrary_project/cll/middleware.py
CodeListLibrary_project/cll/settings.py
CodeListLibrary_project/cll/static/js/clinicalcode/redesign/components/tooltipFactory.js
CodeListLibrary_project/cll/templates/clinicalcode/adminTemp/admin_mig_phenotypes_dt.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/create.html

See:
- #1302
- #1303
- #1305
- #1307
- #1311
- #1312

Migration, Phenotype ownership of children, sessions & tooltips

---

CodeListLibrary_project/clinicalcode/entity_utils/api_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/concept_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/model_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/cll/static/js/clinicalcode/redesign/components/brandurls.js
CodeListLibrary_project/cll/templates/cl-docs/contact-us.html
CodeListLibrary_project/cll/templates/clinicalcode/brand/HDRUK/index_HDRUK.html
CodeListLibrary_project/cll/templates/clinicalcode/index.html

Reformat workspace

---

CodeListLibrary_project/clinicalcode/views/adminTemp.py

Added sequence fix to fix id sequence instead of 1

Sequence fix for the publishgenericentity

---

CodeListLibrary_project/clinicalcode/urls_generic_entity.py
CodeListLibrary_project/clinicalcode/views/adminTemp.py

Made the endpoint to fix the Breathe phenotypes using SQL. Need to be run on demo. Works locally on fresh backup

Adding fix validations for Breathe phenotypes

---

CodeListLibrary_project/clinicalcode/entity_utils/publish_utils.py
CodeListLibrary_project/clinicalcode/templatetags/entity_publish_renderer.py

As the modal to choose the phenotype has been fixed. 
The concept error handling works differently now.

fix publish concept versioning

---

CodeListLibrary_project/clinicalcode/views/Decline.py
CodeListLibrary_project/clinicalcode/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/views/Publish.py
CodeListLibrary_project/cll/templates/components/details/outputs/version_history.html

There is small bug in the detail page showing no history when you are logout.
And at the same time there was a typo in the GenericEntity file regarding the publish date. 
Changes to see the publish date when you are authorized is done as well.
Publish date now showing only when actually published

Pubish date fix

---

CodeListLibrary_project/cll/static/js/clinicalcode/components/navigation.js
CodeListLibrary_project/cll/static/scss/components/_search-navigation.scss
CodeListLibrary_project/cll/static/scss/main.scss
CodeListLibrary_project/cll/templates/components/base/navigation.html
CodeListLibrary_project/cll/templates/components/base/profile_menu.html
CodeListLibrary_project/cll/templates/components/navigation/search_navigation.html

Added more features to the navbar such as:
The navigation search bar on the top
My collection link from the account dropdown
#1413 
#1413

Adding more bug fixes of navbar before prod

---

CodeListLibrary_project/cll/static/scss/pages/home/base.scss

Just a small fix to the list of showing features

small fix to the landing page features list

---

CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py

…ntrol this from Admin/brands
Remove Phenotype Library collection #356

allow to exclude collections from brand filters in search page and co… #356

---

CodeListLibrary_project/clinicalcode/tests/testing_playbook.md

Testing Docs

---

CodeListLibrary_project/clinicalcode/entity_utils/search_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/template_utils.py
CodeListLibrary_project/clinicalcode/views/GenericEntity.py
CodeListLibrary_project/cll/static/js/clinicalcode/forms/clinical/conceptCreator.js
CodeListLibrary_project/cll/static/js/clinicalcode/services/conceptSelectionService.js
docs/sql-scripts/examine_codelist.sql

See:
- #1534 
- #1535
Partial implementation of:
- #1533
Continuation of:
- #1531

Template descendant search changes

---

CodeListLibrary_project/clinicalcode/templatetags/cl_extras.py
CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/create.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/select.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/detail/detail.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/search/search.html

Contextual open graphs and keywords

---

CodeListLibrary_project/cll/static/js/clinicalcode/forms/entityCreator.js
CodeListLibrary_project/cll/static/js/clinicalcode/utils.js
CodeListLibrary_project/cll/templates/components/create/inputs/markdown.html

Fix markdown rendering post-compression

---

CodeListLibrary_project/clinicalcode/tests/testing_playbook.md

Adding url  to the documentation

Adding the url of remote test results netlify

---

CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/clinicalcode/models/Template.py
CodeListLibrary_project/clinicalcode/views/View.py
CodeListLibrary_project/cll/templates/clinicalcode/about/reference_data.html

fix: vary render status of components and/or data as described by template properties

---

CodeListLibrary_project/cll/settings.py
docker/requirements/base.txt

Added the working copy of the blog.
We need to ensure that we use only related packages.
Explicit verison of cms packages have been added

working test cms package

---

CodeListLibrary_project/clinicalcode/entity_utils/entity_db_utils.py
CodeListLibrary_project/clinicalcode/urls.py
CodeListLibrary_project/clinicalcode/views/adminTemp.py
CodeListLibrary_project/cll/templates/clinicalcode/adminTemp/admin_temp_tool.html
CodeListLibrary_project/cll/templates/components/details/outputs/phenoflowid.html
CodeListLibrary_project/dynamic_templates/clinical_coded_phenotype.json
CodeListLibrary_project/dynamic_templates/structured_data_algorithm_phenotype.json

Merge requires updating Clinical-Coded and Structured Data Algorithm phenotypes

Update templates, FE and adminTemp for phenoflow changes

---

CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py
CodeListLibrary_project/cll/static/js/clinicalcode/components/entitySelector.js
CodeListLibrary_project/cll/static/js/clinicalcode/components/fuzzyQuery.js
CodeListLibrary_project/cll/static/js/clinicalcode/components/modal.js
CodeListLibrary_project/cll/static/js/clinicalcode/components/tagify.js
CodeListLibrary_project/cll/static/js/clinicalcode/components/toastNotification.js
CodeListLibrary_project/cll/static/js/clinicalcode/components/tooltipFactory.js
CodeListLibrary_project/cll/static/js/clinicalcode/components/virtualisedList/virtualList.js
CodeListLibrary_project/cll/static/js/clinicalcode/forms/clinical/publicationCreator.js
CodeListLibrary_project/cll/static/js/clinicalcode/forms/entityCreator/utils.js
CodeListLibrary_project/cll/static/js/clinicalcode/forms/stringInputListCreator.js
CodeListLibrary_project/cll/static/js/clinicalcode/services/collectionService.js
CodeListLibrary_project/cll/static/js/clinicalcode/services/referenceDataService.js
CodeListLibrary_project/cll/static/js/clinicalcode/utils.js
CodeListLibrary_project/cll/static/scss/_methods.scss
CodeListLibrary_project/cll/templates/clinicalcode/about/reference_data.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/create.html
CodeListLibrary_project/cll/templates/clinicalcode/generic_entity/creation/select.html
CodeListLibrary_project/cll/templates/clinicalcode/moderation/index.html
CodeListLibrary_project/cll/templates/clinicalcode/profile/my_collection.html
CodeListLibrary_project/cll/templates/components/create/inputs/clinical/concept.html
CodeListLibrary_project/cll/templates/components/create/inputs/clinical/publication.html
CodeListLibrary_project/cll/templates/components/create/inputs/generic/ontology.html
CodeListLibrary_project/cll/templates/components/create/inputs/grouped_enum.html
CodeListLibrary_project/cll/templates/components/create/inputs/markdown.html
CodeListLibrary_project/cll/templates/components/create/inputs/string_inputlist.html
CodeListLibrary_project/cll/templates/components/create/inputs/tagbox.html

See associated issues for details:
- #1693 
- #1694
- Contextual data now rendered within `<script type="application/json" />` elements
- Instances where `unquote` were used should be replaced with the `safely-unquote` method in future, defined within `scss/_methods.scss`

fix!: safer data implementation & fix deprecated SCSS unquote usage

---

CodeListLibrary_project/clinicalcode/entity_utils/email_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/publish_utils.py
CodeListLibrary_project/clinicalcode/tasks.py
CodeListLibrary_project/clinicalcode/templatetags/entity_publish_renderer.py
CodeListLibrary_project/cll/templates/clinicalcode/email/email_content.html

Adding availability to see emails if it sent to the staff users

Fixing the email notification bug 

---

CodeListLibrary_project/clinicalcode/audit/request_signals.py
CodeListLibrary_project/clinicalcode/entity_utils/constants.py
CodeListLibrary_project/clinicalcode/entity_utils/create_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/entity_db_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/permission_utils.py
CodeListLibrary_project/clinicalcode/entity_utils/publish_utils.py
CodeListLibrary_project/clinicalcode/templatetags/entity_publish_renderer.py
CodeListLibrary_project/clinicalcode/templatetags/entity_renderer.py
CodeListLibrary_project/clinicalcode/views/GenericEntity.py
CodeListLibrary_project/clinicalcode/views/adminTemp.py
CodeListLibrary_project/clinicalcode/views/dashboard/BrandAdmin.py
CodeListLibrary_project/clinicalcode/views/dashboard/targets/BaseTarget.py
CodeListLibrary_project/clinicalcode/views/dashboard/targets/HDRNDataAssetTarget.py
CodeListLibrary_project/clinicalcode/views/dashboard/targets/OrganisationTarget.py
CodeListLibrary_project/clinicalcode/views/dashboard/targets/TemplateTarget.py
CodeListLibrary_project/cll/static/js/clinicalcode/components/autocomplete.js
CodeListLibrary_project/cll/static/js/clinicalcode/services/dashboardService/components/orgAuthoritySelector.js
CodeListLibrary_project/cll/static/js/clinicalcode/services/dashboardService/components/orgMemberSelector.js
CodeListLibrary_project/cll/static/scss/components/_inputs.scss
CodeListLibrary_project/cll/templates/components/base/profile_menu.html

fix: dashboard autocomplete & fk selection
fix: rendering of pub & mod
fix: visibility perms

HDRN iteration

---

.github/workflows/pr-title-commitlint.yaml

fix: linting ci
